name: DevSecOps CI

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # =========================
      # STAGE 1: SECRET SCANNING
      # =========================
      - name: Secret Scanning (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: dir --source . --verbose --exit-code 1

      # =========================
      # STAGE 2: SAST (SonarCloud)
      # =========================
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=fomogbehin07 \
            -Dsonar.projectKey=fomogbehin07_DevSecOps_Simple_Pipeline
            -Dsonar.sources=.

      # =========================
      # STAGE 3: SCA (Snyk)
      # =========================
      - name: SCA (Snyk)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high

      # =========================
      # STAGE 4: SBOM (Trivy)
      # =========================
      - name: SBOM Generation (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: cyclonedx
          output: sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-file
          path: sbom.json

      # =========================
      # STAGE 5: DAST (ZAP)
      # =========================
      - name: DAST (OWASP ZAP)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://example.com'
